Restaurant-App/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using Restaurant_App.Models;
using Restaurant_App.Services.Interfaces;
using Restaurant_App.ViewModels;
using Restaurant_App.ViewModels.Abouts;
using Restaurant_App.ViewModels.Informations;

namespace Restaurant_App.Controllers
{
    public class AboutController : Controller
    {
        private readonly IAboutService _aboutService;

        public AboutController(IAboutService aboutService)
        {
            _aboutService = aboutService;
        }

        public async Task<IActionResult> About()
        {
          var aboutResult = await _aboutService.GetAllAsync();

           
          AboutVM aboutVM = new AboutVM
           {
               About = aboutResult?.Select(m => new About
               {
                   Image = m.Image,
                   Title = m.Title,
                   Description = m.Description
               }).ToList() ?? new List<About>()
           };
            return View(aboutVM);
        }
    }

}

Restaurant-App/Controllers/BookingController.cs
using Microsoft.AspNetCore.Mvc;

namespace Restaurant_App.Controllers
{
    public class BookingController : Controller
    {
        public IActionResult Booking()
        {
            return View();
        }
    }
}

Restaurant-App/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace Restaurant_App.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Contact()
        {
            return View();
        }
    }
}

Restaurant-App/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;

namespace Restaurant_App.Controllers
{
    public class MenuController : Controller
    {
        public IActionResult Menu()
        {
            return View();
        }
    }
}

Restaurant-App/Views/Shared/Components/Header/Default.cshtml
<div class="container-xxl position-relative p-0">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0">
        <a href="#" class="navbar-brand p-0">
            <h1 class="text-primary m-0"><i class="fas fa-utensils me-3"></i>Restoran</h1>
            @* <img src="~/assets/img/logo.png" alt="Logo"> *@
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="fas fa-bars"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0 pe-4">
                <a asp-controller="Home" asp-action="Index" class="nav-item nav-link">Home</a>
                <a asp-controller="About" asp-action="About" class="nav-item nav-link">About</a>
                <a asp-controller="Service" asp-action="Service" class="nav-item nav-link">Service</a>
                <a asp-controller="Menu" asp-action="Menu" class="nav-item nav-link">Menu</a>
                <a asp-controller="Booking" asp-action="Booking" class="nav-item nav-link">Booking</a>
                <a asp-controller="Contact" asp-action="Contact" class="nav-item nav-link">Contact</a>
            </div>
            <a asp-controller="Account" asp-action="Login" class="btn btn-primary py-2 px-4">Sign In</a>
        </div>
    </nav>
</div>